name: yummy
description: Yummy is a food platform for customers to order food from a wide variety of restaurants

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.10.0+4   # для камеры
  intl: ^0.18.1
  flutter_riverpod: ^2.4.5

  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  cloud_firestore: ^4.13.2

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
